gQuezada/20180522.md

feat(init) project

---

kdanitzad/ejemploFusionBranch.md

agregando my new md

---

dive0420/23052018.md

Prueba comandos branch y notas de clase 23052018

Branch prueba

---

salvadorlavariega/23-05-2018.md

notas sobre git

---

juancarmona26/ApuntesJDD180523.md

Se modifica archivo de apuntes del día de hoy 23-05-2018.

Apuntes 180523

---

dive0420/24052018.md

Nota clase 24052018

---

chrigarc/clase3.md

Te comparto las notas de la clase
Temas vistos
* Creación de variables
* Ciclos
* Uso de Map
* Y enlaces de bibliografía

Notas de la tercer clase, ECMAScript6

---

juancarmona26/Apuntes180524.md

Apuntes de JavaScript y ECMAScript6.

Apuntes 2018-05-24

---

velazquezsys/README_22052018.md
velazquezsys/README_23052018.md
velazquezsys/README_24052018.md

ECMAScript

---

chrigarc/clase6.md

Notas de la 6 clase, tipos de datos especiales y clousures

---

chrigarc/clase7.md

Notas de la clase 7

---

chrigarc/ejercicio3.md

De un algoritmo matematico libre a elegir realizar el proceso de que marca TDD, en lugar de código generar pseudocódigo

Ejercicio - Pruebas unitarias

---

RubensTen/04-06-2018/README.md
RubensTen/README-NOTAS-01-06-2018.md

Notas de clase 01-06-2018

---

salvadorlavariega/tddEjercicio/bubbleSort.md

Inicie un pseudocodigo para desarrollar mediante TDD el algoritmo de ordenamiento por bubble sort

Test Driven Development for Bubble sort

---

juancarmona26/ApuntesJDD180601.md

Apuntes 180601

---

juancarmona26/pseudocodigoFuncMat/PseudocodigoFibbTDD.md

Practica pseudocodigo función matemática

---

chrigarc/clase10.md
chrigarc/ejercicio4.md
chrigarc/ejercicios_jest/.jshintrc
chrigarc/ejercicios_jest/ejercicio.js

Notas de la clase 10

---

salvadorlavariega/04-06-2018_notas.md

WIP: notas con descripción de tests de repositorios git

---

dive0420/01062018.md
dive0420/04062018.md

Notas de Clase

---

chrigarc/ejercicios_jest/factorial/.jshintrc
chrigarc/ejercicios_jest/factorial/factorial.js
chrigarc/ejercicios_jest/factorial/package.json
chrigarc/ejercicios_jest/factorial/test/test_factorial.js
chrigarc/ejercicios_jest/repositorios_unit.md

Me falta revisar los repositorios

Ejercicio de implementación de pruebas unitarias de algoritmo matematico

---

dive0420/firstUT/app/index.js
dive0420/firstUT/package.json
dive0420/firstUT/test/test.js

unit test 

---

chrigarc/clase_18_junio.md

Clase de herramientas de debug, Memory Tab

---

RubensTen/19-06-2018/README.md

Notas Web components sesion 2 - Template

---

RubensTen/practica-web-components/README-.md
RubensTen/practica-web-components/components/print-items/index.html
RubensTen/practica-web-components/components/toggle-button/index.html
RubensTen/practica-web-components/index.html
RubensTen/practica-web-components/package.json

Webcomponents Practica

---

RubensTen/if-component/README.md
RubensTen/if-component/index.html
RubensTen/if-component/package.json
RubensTen/if-component/render-component/index.html

Component If

---

chrigarc/webcomponent_if/chrigarc-if.html
chrigarc/webcomponent_if/index.html

propuesta de solución para crear un componente que funcione con un if

---

dive0420/domif/dom-if.html
dive0420/domif/index.html

dom-if exercise

---

kdanitzad/ejercicio-martes26junio2018/index.html
kdanitzad/ejercicio-martes26junio2018/kar-if.html

Sin WIP ya que está terminado :)

ejercicio martes 26 junio karla

---

dive0420/magic-tabs/index.html
dive0420/magic-tabs/magic-tabs.html

WIP: Magic tabs

---

dive0420/polymer-application/.gitignore
dive0420/polymer-application/README.md
dive0420/polymer-application/bower.json
dive0420/polymer-application/index.html
dive0420/polymer-application/manifest.json
dive0420/polymer-application/polymer.json
dive0420/polymer-application/src/one-component/one-component.html
dive0420/polymer-application/src/polymer-application/polymer-application.html
dive0420/polymer-application/test/polymer-application/polymer-application_test.html

paper-tabs

---

gQuezada/magic-tabs/index.html
gQuezada/magic-tabs/magic-tabs.html

Examen Guillermo Quezada

---

chrigarc/polymer/magic-poll/.gitignore
chrigarc/polymer/magic-poll/README.md
chrigarc/polymer/magic-poll/bower.json
chrigarc/polymer/magic-poll/index.html
chrigarc/polymer/magic-poll/manifest.json
chrigarc/polymer/magic-poll/mock.json
chrigarc/polymer/magic-poll/polymer.json
chrigarc/polymer/magic-poll/src/home-view/home-view.html
chrigarc/polymer/magic-poll/src/magic-poll-app/magic-poll-app.html
chrigarc/polymer/magic-poll/src/poll-view/poll-view.html
chrigarc/polymer/magic-poll/test/magic-poll-app/magic-poll-app_test.html

src/
magic-poll-app/magic-poll-app.html
views/
home-view.html -> Un cuestionario que pregunte:
* Nombre del poll (input)
* Opciones permitidas (Uso de inputs para crearlas, son dinámicas).
* Botón para crear. Debe guardar y enviar a la página de poll
poll-view.html -> Mostrar la lista de los polls y cuando seleccionen uno, podrán contestarlo, y mostrará la gráfica de pastel con la información actual
https://poll-api-rest.herokuapp.com/polls GET -> Obtiene una lista con todos los polls
https://poll-api-rest.herokuapp.com/poll POST -> Crea un nuevo poll
{
"question": "Example poll",
"options": [{"option": "Option one", "votes": 0}]
}
El id para el poll es autogenerado
https://poll-api-rest.herokuapp.com/vote/:poll_id/:option POST -> Genera un voto para el poll seleccionado en la opción …

Magic Poll 

---

dive0420/magic-poll-app/.gitignore
dive0420/magic-poll-app/README.md
dive0420/magic-poll-app/bower.json
dive0420/magic-poll-app/index.html
dive0420/magic-poll-app/manifest.json
dive0420/magic-poll-app/polymer.json
dive0420/magic-poll-app/src/magic-poll-app-app/magic-poll-app-app.html
dive0420/magic-poll-app/src/views/home-view.html
dive0420/magic-poll-app/src/views/poll-view.html
dive0420/magic-poll-app/test/magic-poll-app-app/magic-poll-app-app_test.html

magic poll

---

dive0420/polymer-application/src/one-component/one-component.html
dive0420/polymer-application/test/polymer-application/polymer-application_test.html

testing taps

---

salvadorlavariega/responsive-table/responsive-table.js

responsive table with css

---

chrigarc/polymer-redux/demo/README.md
chrigarc/polymer-redux/demo/index.html
chrigarc/polymer-redux/demo/manifest.json
chrigarc/polymer-redux/demo/package.json
chrigarc/polymer-redux/demo/polymer.json
chrigarc/polymer-redux/demo/src/demo-app/demo-app.js
chrigarc/polymer-redux/demo/src/home-view/home-view.js
chrigarc/polymer-redux/demo/src/redux/polymer-redux.js
chrigarc/polymer-redux/demo/src/redux/reducers/questions.reducers.js
chrigarc/polymer-redux/demo/src/redux/reducers/reducers.js
chrigarc/polymer-redux/demo/src/redux/reduxMixin.js
chrigarc/polymer-redux/demo/test/demo-app/demo-app_test.html

Practica -  Crear un front para un servicio de poll utilizando redux
Es un simple demo, no realiza los votos y tampoco realiza las llamadas con ajax. Pero conforme se van creando las encuestas cambia el estado y va actualizando la lista

Practica de Redux
